#!/bin/sh

#assume we're in the package dir, but not descended into debian
. ../shellrc
prompt="Enter any key to continue, or \"no\" to exit"


dh_make --single --copyright bsd -e adsb-devs@flightaware.com -f ../pkg.tar.gz

read -p "About to transfer files.  $prompt: " response
case $response in
	[Nn]* ) echo "now exiting"; exit;;
	* ) echo "starting file transfer";;
esac

LINTIAN=1
read -p "Run lintian when the time comes? (yes) : " response
case $response in
	[Nn]* ) LINTIAN=0 ; exit;;
esac

file_source=../files
cp -v $file_source/rules debian/rules
cp -v $file_source/control debian/control
cp -v $file_source/copyright debian/copyright
#cp -v $file_source/changelog debian/changelog
cp -v $file_source/postinst debian/postinst
cp -v $file_source/postrm debian/postrm
rm debian/postinst.ex
rm debian/postrm.ex
#
# Alter changelog
#
#result=""
#i=0
#while read line
#do
#	echo "$line"|grep "nnnn is the bug number">/dev/null
#	grep_result=$?
#	if [ "$i" = "0" ]; then
#		line=`echo "$line" |sed "s/^[^ ]* (${VERSION}-1) unstable/${PKG} (${VERSION}) testing/"`
#		result="$result$line"
#	elif [ "$grep_result" = "0" ]; then
#		line=`echo "$line" |sed "s/\* .*/\* Release ${VERSION}/"`
#		#line=`echo "$line" |sed "s/nnnn is the bug number//"`
#		result="$result\n--$line"
#	elif [ "$line" = "" ]; then
#		result="$result\n$line"
#	else
#		result="$result\n-$line"
#	fi
#	i=`expr $i + 1`
#done <debian/changelog
#echo "$result">debian/changelog
echo "##### copying in changelog"
cp ../changelog debian/changelog

#
# Build package
#

echo "now building package"

dpkg-buildpackage -rfakeroot | tee /home/karl/install.log 2>&1; \

if [ "$LINTIAN" = "0" ]; then
    exit
fi

cp -v $file_source/geterr ~
lintian -Ivi ../${PKG}_${VERSION}*_armhf.changes |tee ~/lintian.log 2>&1; $file_source/geterr; \
rm ~/geterr

echo "These are the errors caught by lintian:"
echo "############################################################"
cat ~/linterr
echo "############################################################"
